### ISSUE TITLE
[BE] front-end 요청사항에 따른 API 수정

### ISSUE THREAD

**Issue by khk811** [42MVP/back-end#40]
### Description
front-end 팀에서 채팅 API 관련 데이터 항목 추가 및 수정을 부탁하셔서 해당 내용을 수정합니다.

### 수정 내역
- **이미 입장한 방에 다시 입장하려 하는 경우 response가 성공으로 들어오는 케이스를 수정:**  
DB에는 중복으로 들어가지 않으나 응답이 성공으로 오게되면 프런트측에서 사용자에게 해당 상황에 대해 알려주기 어렵습니다.
- **ChatRoomDataDTO(ChatInfo) 레벨에서 요청 유저 본인의 role과 abong 타임, isChannel 로 채널인지 여부 추가:**
-  **ChatRoomDataDTO(ChatInfo) 내에서 users배열 내에는 요청 유저 본인은 제외한 채 전송:**
예를들어 DM의 경우에는 내부 유저가 두 명 이겠지만 본인을 제외한 형태이므로 배열 내에 상대 user에 대한 정보만 들어있습니다.
- **ChatRoomDataDTO(ChatInfo) 쪽에 abong유저 정보 삭제:** 
ChatUserDataDTO 내에 abongTime이 존재하고 다른 유저의 아봉시간은 서로 몰라도 되기 때문에 
-  아봉이 한 번이라도 적용된 user에 한해서는 별 다른 처리 없이 **마지막으로 적용된 abongTime**을,
아봉이 **한 번도 적용이 안 된 user의 경우에는 초기값**(1970-01-01T00:00:00.000Z)을 보내도록 수정

### To-do
- [x] 입장 내역이 이미 존재하는 경우 예외처리 (?)
- [x] ChatRoomDataDto에 요청 유저 role, abongtime 채널의 isChannel 추가
- [x] ChatRoomDataDto 내 ChatUserDto에서 요청 유저를 제외하고 보내기
- [x] ChatRoomDataDto에서 abong 유저 목록 삭제
- [x] default abong 적용
- [x] 채널 밖에 있는 유저도 Ban하도록 로직 수정

**Comment by chaejin-jen** [comment]
- [x] 채널 밴 - 채널 밖에 있는 유저 밴이 필요

**Comment by chaejin-jen** [comment]
@khk811 
- [x] mute
    - [x] 채팅 룸 리스트의 user에 정보에서 타겟 유저가 없어짐
    - [x] 전달한 muteTime은 정상적이나, DB에 이상한 값으로 저장됨
        - local 을 맞춰야 할까요?
        - 저는 그냥 new Date() 로 했습니다..
        - (오전 11시 45분쯤 테스트 함 -> 9시간 빠름 UTC 기준??) ![image](https://github.com/42MVP/back-end/assets/73324850/6380a173-5ec2-4309-bc9c-d9ed9c66380f)

**Comment by khk811** [comment]
@chaejin-jen 
- ```채팅 룸 리스트의 user정보에서 타겟 유저가 없어짐``` 이 부분에 대해서 조금만 더 구체적으로 설명해주실수 있나요?
그니까 요청한 유저가 user[]에서 없어진다는 의미신가요? 
- muteTime의 경우 kanghyki님이 요청해주신 값을 그대로 넣어서
```  private defaultMuteTime: Date = new Date('1970-01-01T00:00:00.000Z'); ``` 
이렇게 선언해도 DB 내에서는 9시간 뒤의 시간이 기록이 됩니다. 왜 이렇게 기록되는지는 잘 모르겠습니다. 저도 이 부분에 대해 좀 더 찾아봐야 알것 같습니다. 
- 제가 muteTime을 in-memory로 저장하면서 간과한게 하나 있습니다.
<유저 아이디 : muteTime > 이런 key:value 형태로 저장을 하고 있었는데, 채팅 방 마다 muteTime이 다 다르기 때문에 유저 아이디 뿐만 아니라 방에 대한 정보도 in-memory에 추가로 저장되어야 할것 같습니다. 일단 이러한 부분은 감안하시고 테스트를 해주세요. 이슈를 따로 등록해서 수정하겠습니다.

**Comment by chaejin-jen** [comment]
@khk811 
 
> * `채팅 룸 리스트의 user정보에서 타겟 유저가 없어짐` 이 부분에 대해서 조금만 더 구체적으로 설명해주실수 있나요?
>   그니까 요청한 유저가 user[]에서 없어진다는 의미신가요?

네 맞습니다 !

**Comment by chaejin-jen** [comment]
- [x] @Get(':username'), param 으로 받는게 아니라, 토큰에서 ExtractId 해야 함. param 없어도 받을 수 있나요?

**Comment by khk811** [comment]
@chaejin-jen 
채팅 룸 리스트에서 parameter를 삭제했습니다. 현재 get으로 localhost:3000/chat (뒤에 경로 없이) 으로 요청을 보내면 채팅룸 리스트가 가는걸로 수정했습니다. /chat 뒤에 올 path는 일단 지금은 없이 구현했습니다.
