### ISSUE TITLE
[BE] 채팅 API 관련 다양한 수정사항

### ISSUE THREAD

**Issue by khk811** [42MVP/back-end#44]
### Description
채팅 부분에 관련된 다양한 수정사항들을 처리합니다.

### To-do
- [x] #42 
- [x] DB에 저장되는 mutetime을 UTC로 변경
- [x] 새로고침시 소켓 재연결에 따른 handleConnection 수정
- [x] 채팅 소켓 응답 데이터 수정
- [x] 채팅유저 un-Ban 일때 DB에서 삭제
