### ISSUE TITLE
[BE] 유저 파트 빠진 부분 구현

### ISSUE THREAD

**Issue by sinryuji** [42MVP/back-end#47]
### To-Do
- [x] reissue await 추가
- [x] 유저 닉네임 검색
- [x] 모든 유저 리스트
