### ISSUE TITLE
[BE] 유저 관련 추가 구현

### ISSUE THREAD

**Issue by sinryuji** [42MVP/back-end#51]
### Description
DTO, 검색 부분에서 빠진 부분 추가 구현합니다.

### To-Do
- [x] User 검색 Response DTO
- [x] User 검색 시 검색어로 시작하는 검색
- [x] 친구 리스트 Response DTO
- [x] 게임 히스토리 Response DTO
- [x] 팔로우, 블락 유저 아이디 토큰에서 추철하도록
- [x] 업적 리팩토링
