### ISSUE TITLE
[BE] 채팅 유저 역할, 상태 변경 API 작성

### ISSUE THREAD

**Issue by khk811** [42MVP/back-end#6]
### Description
채팅방 내에 존재하는 유저의 권한 변경 및 상태 변경하는 API를 작성합니다.

![Image](https://github.com/42MVP/back-end/assets/26704946/a278a39a-85e0-435e-9000-c2b97733039d)

스크린샷에 강조된 상태버튼들을 눌렀을때 권한과 상태가 변경(on/off) 되는 걸 감안하고 작성을 할 예정입니다.
admin 권한 부여와 kick, ban, mute를 진행할때에는 변경을 실행하는 유저의 권한을 알아야 하기 떄문에 다른 api에 비해 쿼리 파라미터 등 리퀘스트에 필요한 데이터가 많아질것 같습니다.

### To-do
- [x] 간단한 형태의 chatUserStatus 변경 API 작성
- [x] Notion API 명세서 수정 (상태 변경 API 통합)
- [x] 작성된 changerole, changeStatus API의 조건 확인 로직 추가

### ETC
- (7월 11일 오후 3시 기준) API 명세서에는 유저의 추방, 강퇴, 아봉이 각각 나뉘어 있는데, 추방, 강퇴 상태가 DB에 저장되는 관계로 DELETE, POST가 아니라 PATCH로 진행되어야 할것 같아서 수정합니다.

**Comment by khk811** [comment]
채팅 유저 역할, 상태 변경시 해당 API를 요청하는 유저의 id (execute 하는 유저; execid) 와 역할이 변경되는 타겟 유저의 updateChatUserDto가 필요하도록 변경하였습니다. 원래는 Query에 여러 정보를 썼었는데 Dto를 쓰는 편이 query양이 줄어서 url이 상대적으로 깔끔할것 같습니다.
