### ISSUE TITLE
[BE] 채널 탐색, 채널 업데이트, 초대 API 작성

### ISSUE THREAD

**Issue by khk811** [42MVP/back-end#7]
### Description
채널 탐색과 업데이트, 채널에 유저 초대시 사용할 API를 작성합니다.

### To-do
- [x] 채널에 유저 초대 API 작성
- [x] 채널 탐색 API 작성
- [x] 채널 업데이트 API 작성
- [x] API 명세서에 해당 명세 작성
