### ISSUE TITLE
[BE] 구체적인 로직 추가 작성

### ISSUE THREAD

**Issue by khk811** [42MVP/back-end#8]
### Description
작성한 기본기능만 동작하는 로직에 추가적으로 필요한 로직을 첨가합니다.

### To-do
- [x] 채널 생성시 DM과 채팅방 생성 로직을 분리하기 
- [x] 채널 업데이트에서 기존 모드 확인하는 로직 추가
- [x] 채널 업데이트에서 채널 이름 변경하는 부분 막기
